
#ifndef HTTP_ZX_TEENSY_H
#define HTTP_ZX_TEENSY_H

typedef enum {
    HTTP_STR_ADDRESS,
    HTTP_STR_WAIT_IP,
    HTTP_STR_WAIT_NTP,
    HTTP_STR_WAIT_WIFI,
    HTTP_STR_HTTP_PREFIX,
    HTTP_STR_HTTP_200,
    HTTP_STR_HTTP_201,
    HTTP_STR_HTTP_400,
    HTTP_STR_HTTP_403,
    HTTP_STR_HTTP_404,
    HTTP_STR_HTTP_405,
    HTTP_STR_HTTP_409,
    HTTP_STR_HTTP_412,
    HTTP_STR_HTTP_413,
    HTTP_STR_HTTP_501,
    HTTP_STR_HTTP_507,
    HTTP_STR_HTTP_100,
    HTTP_STR_HTTP_204,
    HTTP_STR_HTTP_207,
    HTTP_STR_CONTENT_LENGTH,
    HTTP_STR_CONTENT_LENGTH_ZERO,
    HTTP_STR_CONTENT_TYPE,
    HTTP_STR_XML_CONTENT_TYPE,
    HTTP_STR_CONNECTION_CLOSE,
    HTTP_STR_ALLOW,
    HTTP_STR_DAV,
    HTTP_STR_TEXT_PLAIN,
    HTTP_STR_TEXT_HTML,
    HTTP_STR_BINARY_TYPE,
    HTTP_STR_DIRECTORY_TYPE,
    HTTP_STR_HTML_BEGIN,
    HTTP_STR_HTML_LINK,
    HTTP_STR_HTML_LINK_END,
    HTTP_STR_HTML_END,
    HTTP_STR_HEX,
    HTTP_STR_XML_DECL,
    HTTP_STR_XML_MULTI_BEGIN,
    HTTP_STR_XML_MULTI_END,
    HTTP_STR_XML_PATCH_BEGIN,
    HTTP_STR_XML_RESPONSE_BEGIN,
    HTTP_STR_XML_HREF_END,
    HTTP_STR_XML_PROP_OK,
    HTTP_STR_XML_PROP_END,
    HTTP_STR_XML_PROP_FORBIDDEN,
    HTTP_STR_XML_PATCH_END,
    HTTP_STR_XML_PROTECTED,
    HTTP_STR_XML_TAG_BEGIN,
    HTTP_STR_XML_EMPTY_END,
    HTTP_STR_XML_DISPLAY_BEGIN,
    HTTP_STR_XML_DISPLAY_END,
    HTTP_STR_XML_RESOURCE_DIR,
    HTTP_STR_XML_RESOURCE_FILE,
    HTTP_STR_XML_LENGTH_BEGIN,
    HTTP_STR_XML_LENGTH_END,
    HTTP_STR_XML_TYPE_BEGIN,
    HTTP_STR_XML_TYPE_END,
    HTTP_STR_XML_MODIFIED_BEGIN,
    HTTP_STR_XML_MODIFIED_END,
    HTTP_STR_XML_CREATED_BEGIN,
    HTTP_STR_XML_CREATED_END,
    HTTP_STR_XML_ETAG_BEGIN,
    HTTP_STR_XML_ETAG_END,
    HTTP_STR_XML_AMP,
    HTTP_STR_XML_APOS,
    HTTP_STR_XML_GT,
    HTTP_STR_XML_LT,
    HTTP_STR_XML_QUOT,
    HTTP_STR_ALLPROP,
    HTTP_STR_PROPNAME,
    HTTP_STR_PROPERTYUPDATE,
    HTTP_STR_SET_TAG,
    HTTP_STR_SET_PREFIX,
    HTTP_STR_REMOVE_TAG,
    HTTP_STR_REMOVE_PREFIX,
    HTTP_STR_EXPECT,
    HTTP_STR_DEPTH,
    HTTP_STR_DESTINATION,
    HTTP_STR_OVERWRITE,
    HTTP_STR_DISPLAYNAME,
    HTTP_STR_RESOURCETYPE,
    HTTP_STR_CONTENTLENGTH_PROP,
    HTTP_STR_CONTENTTYPE_PROP,
    HTTP_STR_LASTMODIFIED,
    HTTP_STR_CREATIONDATE,
    HTTP_STR_ETAG,
    HTTP_STR_DATE_HTTP_FORMAT,
    HTTP_STR_DATE_ISO_FORMAT,
    HTTP_STR_SUN,
    HTTP_STR_MON,
    HTTP_STR_TUE,
    HTTP_STR_WED,
    HTTP_STR_THU,
    HTTP_STR_FRI,
    HTTP_STR_SAT,
    HTTP_STR_JAN,
    HTTP_STR_FEB,
    HTTP_STR_MAR,
    HTTP_STR_APR,
    HTTP_STR_MAY,
    HTTP_STR_JUN,
    HTTP_STR_JUL,
    HTTP_STR_AUG,
    HTTP_STR_SEP,
    HTTP_STR_OCT,
    HTTP_STR_NOV,
    HTTP_STR_DEC,
    HTTP_STR_COPY,
    HTTP_STR_DELETE,
    HTTP_STR_GET,
    HTTP_STR_HEAD,
    HTTP_STR_MOVE,
    HTTP_STR_MKCOL,
    HTTP_STR_OPTIONS,
    HTTP_STR_PUT,
    HTTP_STR_PROPFIND,
    HTTP_STR_PROPPATCH,
    HTTP_STR_AT_SEND,
    HTTP_STR_AT_CLOSE,
    HTTP_STR_AT_ECHO_OFF,
    HTTP_STR_AT_IP,
    HTTP_STR_AT_MUX,
    HTTP_STR_AT_SERVER_START,
    HTTP_STR_AT_SERVER_STOP,
    HTTP_STR_AT_IP_REPLY,
    HTTP_STR_AT_SEND_OK,
    HTTP_STR_AT_OK,
    HTTP_STR_NO_IP,
    HTTP_STR_HREF_END,
    HTTP_STR_COUNT
} http_string_t;

static const char* const PROGMEM HTTP_STRINGS[] = {
    " > Address: ",
    " > Waiting for IP address",
    " > Waiting for WiFi NTP",
    " > Waiting for WiFi",
    "HTTP/1.1 ",
    "200 OK",
    "201 Created",
    "400 Bad Request",
    "403 Forbidden",
    "404 Not Found",
    "405 Method Not Allowed",
    "409 Conflict",
    "412 Precondition Failed",
    "413 Content Too Large",
    "501 Not Implemented",
    "507 Insufficient Storage",
    "HTTP/1.1 100 Continue\r\n\r\n",
    "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n",
    "HTTP/1.1 207 Multi-Status\r\n",
    "Content-Length: ",
    "0\r\n",
    "Content-Type: ",
    "application/xml; charset=utf-8\r\n",
    "Connection: close\r\n\r\n",
    "Allow: OPTIONS, GET, HEAD, PUT, DELETE, COPY, MOVE, MKCOL, PROPFIND, PROPPATCH\r\n",
    "DAV: 1\r\n",
    "text/plain",
    "text/html",
    "application/octet-stream",
    "httpd/unix-directory",
    "<html><body>",
    "<a href=\"",
    "</a><br>",
    "</body></html>",
    "0123456789ABCDEF",
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n",
    "<D:multistatus xmlns:D=\"DAV:\">\r\n",
    "</D:multistatus>\r\n",
    "<D:multistatus xmlns:D=\"DAV:\"><D:response><D:href>",
    "<D:response><D:href>",
    "</D:href><D:propstat><D:prop>",
    "</D:prop><D:status>HTTP/1.1 200 OK</D:status>",
    "</D:propstat></D:response>\r\n",
    "</D:prop><D:status>HTTP/1.1 403 Forbidden</D:status>",
    "</D:propstat></D:response></D:multistatus>\r\n",
    "<D:error><D:cannot-modify-protected-property/></D:error>",
    "<D:",
    "/>",
    "<D:displayname>",
    "</D:displayname>",
    "<D:resourcetype><D:collection/></D:resourcetype>",
    "<D:resourcetype/>",
    "<D:getcontentlength>", "</D:getcontentlength>",
    "<D:getcontenttype>",
    "</D:getcontenttype>", "<D:getlastmodified>",
    "</D:getlastmodified>",
    "<D:creationdate>", "</D:creationdate>",
    "<D:getetag>&quot;",
    "&quot;</D:getetag>",
    "&amp;",
    "&apos;",
    "&gt;",
    "&lt;",
    "&quot;",
    "allprop",
    "propname",
    "propertyupdate",
    "<set",
    ":set",
    "<remove",
    ":remove",
    "\nExpect:",
    "\nDepth:",
    "\nDestination:",
    "\nOverwrite:",
    "displayname",
    "resourcetype",
    "getcontentlength",
    "getcontenttype",
    "getlastmodified",
    "creationdate",
    "getetag",
    "%s, %02d %s %04d %02d:%02d:%02d GMT",
    "%04d-%02d-%02dT%02d:%02d:%02dZ",
    "Sun",
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    "COPY ",
    "DELETE ",
    "GET ",
    "HEAD ",
    "MOVE ",
    "MKCOL ",
    "OPTIONS ",
    "PUT ",
    "PROPFIND ",
    "PROPPATCH ",
    "AT+CIPSEND=",
    "AT+CIPCLOSE=",
    "ATE0",
    "AT+CIFSR",
    "AT+CIPMUX=1",
    "AT+CIPSERVER=1,80",
    "AT+CIPSERVER=0",
    "+CIFSR:STAIP,\"",
    "SEND OK",
    "OK",
    "0.0.0.0",
    "\">"
};

#endif
