
#ifndef STRINGS_ZX_TEENSY_H
#define STRINGS_ZX_TEENSY_H

typedef enum {
    STRING_CANCEL,
    STRING_RESTART,
    STRING_DISABLE,
    STRING_OPEN_SETTINGS,
    STRING_OPEN_CONFIGS,
    STRING_OPEN_BROWSER,
    STRING_OPEN_ROMS,
    STRING_OPEN_HTTP_SERVER,
    STRING_OPEN_SAVE_STATE_SLOT,
    STRING_OPEN_LOAD_STATE_SLOT,
    STRING_UPDATE_FW,
    STRING_BOOT_MENU,
    STRING_ENABLE_MENU_IN_GAME,
    STRING_ENABLE_DIVMMC,
    STRING_ENABLE_DIVMMC_RAM,
    STRING_ENABLE_DIVMMC_ROM,
    STRING_ENABLE_IF1,
    STRING_ENABLE_MF128,
    STRING_ENABLE_USB,
    STRING_ENABLE_FIRE_BUTTONS,
    STRING_ENABLE_UART,
    STRING_ENABLE_MODEM,
    STRING_UPDATE_RTC_WIFI_NTP,
    STRING_SET_NTP_TZ,
    STRING_WIFI_NTP_WAITING,
    STRING_RTC_NOT_SET,
    STRING_ENABLE_FDC,
    STRING_ENABLE_PRINTER,
    STRING_ENABLE_LPRINT,
    STRING_CLEAR_PRINTER,
    STRING_LOAD_RTC_CONFIG,
    STRING_LOAD_NETMAN,
    STRING_LOAD_ROM,
    STRING_LOAD_ZXC2,
    STRING_LOAD_ZXC3,
    STRING_LOAD_Z80,
    STRING_LOAD_TZX,
    STRING_LOAD_MDR,
    STRING_MOUNT_SDA,
    STRING_MOUNT_SDB,
    STRING_MOUNT_FDA,
    STRING_MOUNT_FDB,
    STRING_START_HTTP,
    STRING_STOP_HTTP,
    STRING_OPEN_TAPE_BROWSER,
    STRING_OPEN_DEBUG,
    STRINGS_SAVE_STATE,
    STRINGS_SELECT_STATE,
    STRINGS_LOAD_STATE,
    STRING_INTERNAL_ROM,
    STRING_MINUS_12_00_HOURS,
    STRING_MINUS_11_00_HOURS,
    STRING_MINUS_10_00_HOURS,
    STRING_MINUS_9_30_HOURS,
    STRING_MINUS_9_00_HOURS,
    STRING_MINUS_8_00_HOURS,
    STRING_MINUS_7_00_HOURS,
    STRING_MINUS_6_00_HOURS,
    STRING_MINUS_5_00_HOURS,
    STRING_MINUS_4_00_HOURS,
    STRING_MINUS_3_00_HOURS,
    STRING_MINUS_2_00_HOURS,
    STRING_MINUS_1_00_HOURS,
    STRING_PLUS_0_00_HOURS,
    STRING_PLUS_1_00_HOURS,
    STRING_PLUS_2_00_HOURS,
    STRING_PLUS_3_00_HOURS,
    STRING_PLUS_4_00_HOURS,
    STRING_PLUS_5_00_HOURS,
    STRING_PLUS_6_00_HOURS,
    STRING_PLUS_6_30_HOURS,
    STRING_PLUS_7_00_HOURS,
    STRING_PLUS_8_00_HOURS,
    STRING_PLUS_8_30_HOURS,
    STRING_PLUS_9_00_HOURS,
    STRING_PLUS_9_30_HOURS,
    STRING_PLUS_10_00_HOURS,
    STRING_PLUS_10_30_HOURS,
    STRING_PLUS_11_00_HOURS,
    STRING_PLUS_12_00_HOURS,
    STRING_PLUS_12_45_HOURS,
    STRING_PLUS_13_00_HOURS,
    STRING_PLUS_14_00_HOURS,
    STRING_IN_GAME_MF128,
    STRING_IN_GAME_DIVMMC,
    STRING_IN_GAME_RESET,
    STRING_IN_GAME_HARD_RESET,
    STRING_IN_GAME_EXIT_TAPE,
    STRING_IN_GAME_EXIT_BASIC
} menu_string_t;

static const char* const PROGMEM MENU_STRINGS[] = {
    "Back",
    "Save and Reset",
    "Disable and Reset",
    "Edit Settings",
    "Load Configuration",
    "Browse SD card",
    "Load ROM",
    "Configure HTTP server",
    "Select Save State",
    "Load Saved State",
    "Update firmware and Reset",
    "Boot into Menu",
    "Enable In-game Menu",
    "Enable DivMMC",
    "   Enable 512KB RAM",
    "   Enable DivMMC ROM",
    "Enable Interface 1",
    "Enable Multiface 128",
    "Enable Kempston USB mouse/gamepad",
    "   Enable Fire 2/3/4 buttons",
    "Enable ESP-01S UART",
    "   Enable VTX5000",
    "Update RTC from WiFi NTP",
    "   Set WiFi NTP timezone",
    " > Waiting for WiFi NTP",
    " > RTC not set",
    "Enable +3 FDC",
    "Enable Centronics printer",
    "   Enable ZX LPRINT III",
    " > Clear printer output",
    "Load RTC Setup",
    "Load WiFi Network Manager",
    "Load as ROM cartridge",
    "Load as ZXC2 cartridge",
    "Load as ZXC3 Flash cartridge",
    "Load as Z80 snapshot",
    "Load as tape image",
    "Load with Microdrive Emulator",
    "Mount as DivMMC sda",
    "Mount as DivMMC sdb",
    "Mount as FDD A:",
    "Mount as FDD B:",
    "Start HTTP server",
    "Stop HTTP server",
    "Browse Tape",
    "View debug log",
    "Save State",
    "Select Save State",
    "Load State",
    "Internal ROM",
    "-12:00 hours",
    "-11:00 hours",
    "-10:00 hours",
    "-9:30 hours",
    "-9:00 hours",
    "-8:00 hours",
    "-7:00 hours",
    "-6:00 hours",
    "-5:00 hours",
    "-4:00 hours",
    "-3:00 hours",
    "-2:00 hours",
    "-1:00 hours",
    "+0:00 hours",
    "+1:00 hours",
    "+2:00 hours",
    "+3:00 hours",
    "+4:00 hours",
    "+5:00 hours",
    "+6:00 hours",
    "+6:30 hours",
    "+7:00 hours",
    "+8:00 hours",
    "+8:30 hours",
    "+9:00 hours",
    "+9:30 hours",
    "+10:00 hours",
    "+10:30 hours",
    "+11:00 hours",
    "+12:00 hours",
    "+12:45 hours",
    "+13:00 hours",
    "+14:00 hours",
    "Send NMI to Multiface 128",
    "Send NMI to DivMMC ROM",
    "Reset into Main Menu",
    "Cold Reset into Main Menu",
    "Back and Play Tape",
    "Break into BASIC"
};

#endif
